### ISSUE TITLE
MFMT FTP command support

### ISSUE THREAD

**Issue by tahirijaz24** [giampaolo/pyftpdlib#434] opened 2017-09-15 17:38 UTC
Hi Giampaolo, 

In reference to #201 I will be working on implementing MFMT to help with FTP file synchronization. I wanted request you if you had any thoughts or suggestions? 

-Tahir  

P.S. Hope you had fun in China :)

**Comment by giampaolo** [comment] 2017-10-09 18:49
Closing as duplicate of #201.

**Closed by giampaolo** 2017-10-09 18:49 UTC
