### ISSUE TITLE
Tests fail occasionally (Debian 9/stretch)

### ISSUE THREAD

**Issue by MartinBorg** [giampaolo/pyftpdlib#420] opened 2017-04-07 23:46 UTC
While the test suite of release-1.5.0 runs fine for me (both on single core and quad core), it fails for others, here on eight cores:

```
======================================================================
ERROR: test_list (test_functional.TestUnicodePathNames)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pyftpdlib-1.5.1/pyftpdlib/test/test_functional.py", line 2652, in test_list
    self._test_listing_cmds('list')
  File "/build/python-pyftpdlib-1.5.1/pyftpdlib/test/test_functional.py", line 2639, in _test_listing_cmds
    self.client.retrlines(cmd, ls.append)
  File "/usr/lib/python2.7/ftplib.py", line 453, in retrlines
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 229, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 222, in getresp
    raise error_temp, resp
error_temp: 426 Internal error; transfer aborted.

======================================================================
ERROR: test_mlsd (test_functional.TestUnicodePathNames)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pyftpdlib-1.5.1/pyftpdlib/test/test_functional.py", line 2658, in test_mlsd
    self._test_listing_cmds('mlsd')
  File "/build/python-pyftpdlib-1.5.1/pyftpdlib/test/test_functional.py", line 2639, in _test_listing_cmds
    self.client.retrlines(cmd, ls.append)
  File "/usr/lib/python2.7/ftplib.py", line 453, in retrlines
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 229, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 222, in getresp
    raise error_temp, resp
error_temp: 426 Internal error; transfer aborted.

----------------------------------------------------------------------
Ran 783 tests in 16.884s

FAILED (errors=2, skipped=52)
```

This has been reported as Debian bug: https://bugs.debian.org/856335

Is there any fix? Shall we skip the two failing tests temporarily?

Thanks in advance!

**Comment by MartinBorg** [comment] 2017-04-16 11:11
Note, that on different architectures, different test cases are failing:
 * `test_list` and `test_mlsd` on [amd64]( https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/python-pyftpdlib.html) and [arm64](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/arm64/python-pyftpdlib.html)
 * `test_idle_timeout` on [i386](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/python-pyftpdlib.html)

If there is no other solution, I will skip all three test cases.

(For my applications, this version of pyftpdlib works perfectly fine, btw.)

**Comment by giampaolo** [comment] 2017-04-21 16:49
Unfortunately pyftpdlib unit tests are known for not being stable. That's because a thread-based test server is used in each test. I have been planning to replace that with a multi process test server but I still didn't get around to it.

**Comment by MartinBorg** [comment] 2017-04-22 08:45
Are all tests affected by this? In this case I would just disable automatic test on package build. (I would run them manually, of course.) Or are some cases not based on the threaded server, so we could at least run those automatically?

**Comment by giampaolo** [comment] 2017-04-22 08:46
test_functional.py and test_ssl.py are the ones affected. They are also the most important tests.

**Comment by MartinBorg** [comment] 2017-04-22 10:24
Many thanks! I will change the Debian package, so that `test_functional.py` and `test_functional_ssl.py` are not run automatically on package build, but manually only. That way, it is easy to run the tests without making build daemons fail.

**Comment by giampaolo** [comment] 2017-10-19 09:33
I am trying to stabilize tests as of #386. I recently (yesterday) managed to fix failures on Travis but there is still some work to do. I'm gonna close this issue as a duplicate of #386.

**Closed by giampaolo** 2017-10-19 09:33 UTC
