### ISSUE TITLE
IOLoop throws IOError

### ISSUE THREAD

**Issue by szczav** [giampaolo/pyftpdlib#329] opened 2015-07-01 11:27 UTC
We have FTP server build on pyftpdlib.servers.FTPServer and it handles between 10-50 connections per day. Clients are sending us files - images and XMLs. Some connections are passive, some are active, each user has own account and is authenticated. Usually single upload contains up to few dozens files (10-50 MB), but sometimes bigger companies send us hundreds of files (above 500MB). Sometimes data is send simultanously from few clients and for most of time it works fine. Once in a time (every few months) FTP throws errors:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/asynchat.py", line 158, in handle_read
    self.found_terminator()
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1378, in found_terminator
    self.pre_process_command(line, cmd, arg)
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1484, in pre_process_command
    self.process_command(cmd, arg, **kwargs)
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1495, in process_command
    method(*args, **kwargs)I
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 2277, in ftp_STOR
    self.data_channel.enable_receiving(self._current_type, cmd)
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 709, in enable_receiving
    self.ioloop.modify(self._fileno, self.ioloop.READ)
  File "xxx/local/lib/python2.7/site-packages/pyftpdlib/ioloop.py", line 486, in modify
    self._poller.modify(fd, events)
IOError: [Errno 2] No such file or directory
```

It happens when 2 or 3 clients are sending data in the same time and one client is sending a big amount of data. After the error is raised one client is disconnected and later reconnects. Usually there are few such errors one after another. I'm trying to avoid broken connections because clients send us files using desktop applications which have problems with reconnecting.

I'm fighting with this for quite a long time. Many times I tried to reproduce it by triggering multiple uploads to FTP, but never succeded. I'd be greatful for any help.

**Comment by giampaolo** [comment] 2015-10-06 13:06
It appears the right thing to do here is to consider the client socket as "broken" or "disconnected" and reply with "426" over the command channel.

**Comment by szczav** [comment] 2015-10-06 15:09
Thank you for your reply.

Almost all our clients are using the same desktop application which sends data automatically using FTP. I don't have any access to source code of this app. Clients who were affected by this error normally can send data without any issues. 99.99% of connections is properly handled by our FTP server, so I don't think 426 error is proper response here. 426 would make sense if server wasn't able to handle any of client requests.

If error is raised only very rarely only when there are few concurrent connections then it looks as an issue of pyftpdlib and not something related to client.

**Comment by giampaolo** [comment] 2015-10-06 15:12
What happens after `IOError: [Errno 2] No such file or directory`? Does the client receive a 4XX response? Or it just gets immediately disconnected (both control and data channel?)?

**Comment by szczav** [comment] 2015-10-06 15:28
After error occurs client gets completely disconnected.

There were cases when error was raised, client was disconnected and he immediately reconnected. After a moment error was raised again and again client was disconnected.

**Comment by giampaolo** [comment] 2015-10-06 15:29
Does this happen only on STOR or also on RETR?

**Comment by szczav** [comment] 2015-10-06 15:37
Only on STOR.

**Comment by giampaolo** [comment] 2015-10-06 15:44
I am not sure what action we should take in that case.
To me it appears that it's the client which disconnects or not properly connects, and that causes the exception, so the "proper" action the server should take is to catch that exception and close the socket / connection.

**Comment by giampaolo** [comment] 2015-10-06 15:48
...also what command was issued to establish the data connection? PORT or PASV?
It would be interesting to understand if it happens only with passive or active connections or both.

**Comment by szczav** [comment] 2015-10-06 16:28
Unfortunately I don't have all logs. Older ones were removed. From what I could collect affected connections were established always by PORT. Not many of our clients use passive connections - they do it only when they have to (usually due to their firewall settings). So this not necessarily means passive connections aren't affected.

**Comment by giampaolo** [comment] 2015-10-07 12:50
OK, I have committed a fix attempt. Can you test if it works? Unfortunately I cannot reproduce the issue.

**Comment by szczav** [comment] 2015-10-08 11:43
I also wasn't able to reproduce this error. I'll put fix on our server, but this error appears very rarely. It may take some time before I verify if patch solves the issue.

**Comment by travcunn** [comment] 2015-10-10 17:50
After applying this patch, I am seeing ```IOError: [Errno 2] No such file or directory```:

```
File "ftphosting/cli/management/commands/ftpd.py", line 1635, in push_dtp_data
    self.data_channel.push(data)
 
File "pyftpdlib/handlers.py", line 641, in push
    self.ioloop.modify(self._fileno, self.ioloop.WRITE)
 
File "pyftpdlib/ioloop.py", line 487, in modify
    self._poller.modify(fd, events)
```

**Comment by giampaolo** [comment] 2015-10-22 21:58
I think I have fixed this as of https://github.com/giampaolo/pyftpdlib/commit/917d1e87417ed73a33fd9f847e9556bd0b8e0d71. @szczav can you confirm?

**Comment by szczav** [comment] 2015-10-23 15:43
I tested it and works fine. Today I put it on production server. I'll let you know if there appear any issues.

**Closed** 2015-10-24 15:40 UTC
Labels: bug
